name: Notify on new issue

on:
  issues:
    types: [opened]

jobs:
  tag-a-user:
    runs-on: ubuntu-latest
    if: (github.repository == 'paritytech-actions/github-actions-requests')
    steps:
      - uses: paritytech-actions/issue-comment-tag@v0.1.7
        name: Tag a user or team in an issue comment
        with:
          issue: ${{ github.event.issue.number }}
          team: 'paritytech-actions/gha-review-team'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
